export * from "./public/landingPage/index"
export * from "./public/login/index"
export * from "./public/register/index"
export * from "./private/home/index"
export * from "./private/teams/index"
export * from "./private/events/index"
export * from "./private/sports/index"
export * from "./private/events/information"